development:
  adapter: redis
  url: "redis://interview-redis:6379/1"
  channel_prefix: interview_production

test:
  adapter: redis
  url: "redis://interview-redis:6379/1"
  channel_prefix: interview_production

production:
  adapter: redis
  url: "redis://interview-redis:6379/1"
  channel_prefix: interview_production
